/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
const useSignOn = () => {
  const [formData, setFormData] = useState<FormData>({
    username: '',
    password: '',
    isValidPassword: false,
  });

  const handleUsernameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({
      ...formData,
      username: event.target.value,
    });
  };
  const handlePasswordChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const password = event.target.value;
    const isValidPassword = password.length >= 8;
    setFormData({
      ...formData,
      password,
      isValidPassword,
    });
  };
  const handleSubmit = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
    // submit logic here
  };

  const data: any = { formData };

  const fns: any = { handleUsernameChange, handlePasswordChange, handleSubmit };

  return { data, fns };
};

export default useSignOn;
